# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-13 16:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', '支付成功'), ('PAYING', '待支付'), ('TRADE_FAIL', '支付失败'), ('TRADE_FINSHED', '交易结束'), ('TRADE_CLOSE', '支付关闭')], default='PAYING', max_length=30, verbose_name='订单状态')),
                ('total_amount', models.FloatField(verbose_name='总金额')),
                ('order_no', models.CharField(max_length=100, unique=True, verbose_name='网站订单号')),
                ('trade_no', models.CharField(max_length=100, unique=True, verbose_name='支付宝交易号')),
                ('user_msg', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户留言')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
            },
        ),
    ]
