# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-22 17:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0018_auto_20181221_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithDrawMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(verbose_name='提现金额')),
                ('receive_way', models.CharField(choices=[(0, '支付宝'), (1, '微信'), (3, '银行')], max_length=20, verbose_name='提现方式')),
                ('bank_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='银行类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='提现时间')),
                ('withdraw_status', models.CharField(blank=True, choices=[(0, '提现中'), (1, '提现成功'), (2, '提现失败')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '提现表',
                'verbose_name_plural': '提现表',
            },
        ),
    ]
