# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-22 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0019_withdrawmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmoney',
            name='withdraw_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='提现单号'),
        ),
    ]
