# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-22 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0021_auto_20181222_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('PAYING', '待支付'), ('TRADE_SUCCESS', '支付成功'), ('TRADE_CLOSE', '支付关闭')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='withdrawmoney',
            name='withdraw_status',
            field=models.CharField(choices=[('WITHING', '提现中'), ('SUCCESS', '提现成功'), ('FAIL', '提现失败')], default='WITHING', max_length=20),
        ),
    ]
