# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-22 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0022_auto_20181222_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmoney',
            name='receive_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='提现账号'),
        ),
        migrations.AddField(
            model_name='withdrawmoney',
            name='receive_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='到账时间'),
        ),
        migrations.AddField(
            model_name='withdrawmoney',
            name='user_msg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='用户留言'),
        ),
    ]
