# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-24 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0024_withdrawmoney_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='receive_way',
            field=models.CharField(blank=True, choices=[('ALIPAY', '支付宝'), ('WECHAT', '微信'), ('BANK', '银行')], max_length=20, null=True, verbose_name='支付类型'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_CLOSE', '支付关闭'), ('TRADE_SUCCESS', '支付成功'), ('PAYING', '待支付')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='withdrawmoney',
            name='withdraw_status',
            field=models.CharField(choices=[('WITHING', '提现中'), ('SUCCESS', '提现成功'), ('FAIL', '提现失败')], default='WITHING', max_length=20, verbose_name='提现状态'),
        ),
    ]
