# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0025_auto_20181224_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='receive_way',
            field=models.CharField(choices=[('ALIPAY', '支付宝'), ('WECHAT', '微信'), ('BANK', '银行')], default='ALIPAY', max_length=20, verbose_name='支付类型'),
        ),
    ]
