# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-25 11:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0026_auto_20181224_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收款公司名称')),
                ('c_appid', models.CharField(max_length=32, verbose_name='商家支付宝appid')),
                ('alipay_public_key', models.TextField(verbose_name='支付宝公钥')),
                ('c_private_key', models.TextField(verbose_name='商家私钥')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活状态')),
                ('last_time', models.DateTimeField(blank=True, null=True, verbose_name='最后收款时间')),
            ],
            options={
                'verbose_name': '商家信息管理',
                'verbose_name_plural': '商家信息管理',
            },
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_CLOSE', '支付关闭'), ('PAYING', '待支付'), ('TRADE_SUCCESS', '支付成功')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
    ]
