# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-25 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0027_auto_20181225_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessinfo',
            options={'verbose_name': '商家管理', 'verbose_name_plural': '商家管理'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '订单管理', 'verbose_name_plural': '订单管理'},
        ),
        migrations.AlterModelOptions(
            name='withdrawmoney',
            options={'verbose_name': '提现管理', 'verbose_name_plural': '提现管理'},
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='pay_url',
            field=models.TextField(blank=True, null=True, verbose_name='支付链接'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('PAYING', '待支付'), ('TRADE_CLOSE', '支付关闭'), ('TRADE_SUCCESS', '支付成功')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
    ]
