# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-26 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0032_auto_20181226_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('PAYING', '待支付'), ('TRADE_CLOSE', '支付关闭'), ('TRADE_SUCCESS', '支付成功')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='withdrawmoney',
            name='withdraw_status',
            field=models.CharField(choices=[('0', '申请中'), ('1', '处理中'), ('2', '提现成功'), ('3', '提现失败')], default='WITHING', max_length=20, verbose_name='提现状态'),
        ),
    ]
