# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0034_auto_20181226_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '支付成功'), ('PAYING', '待支付'), ('TRADE_CLOSE', '支付关闭')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='withdrawmoney',
            name='receive_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到账时间'),
        ),
    ]
