# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-26 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0036_auto_20181226_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmoney',
            name='money_flag',
            field=models.BooleanField(default=False, verbose_name='旗帜'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '支付成功'), ('PAYING', '待支付'), ('TRADE_CLOSE', '支付关闭')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
    ]
