# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-26 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0037_auto_20181226_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawmoney',
            name='withdraw_status',
            field=models.CharField(choices=[('0', '处理中'), ('1', '已处理')], default='0', max_length=20, verbose_name='提现状态'),
        ),
    ]
