# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0040_auto_20181227_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_CLOSE', '支付关闭'), ('TRADE_SUCCESS', '支付成功'), ('PAYING', '待支付')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='withdrawmoney',
            name='receive_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='withdrawmoney',
            name='receive_way',
            field=models.CharField(choices=[('ALIPAY', '支付宝'), ('WECHAT', '微信'), ('BANK', '银行')], max_length=20, verbose_name='提现类型'),
        ),
    ]
