# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-28 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0043_auto_20181228_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '支付成功'), ('TRADE_CLOSE', '支付关闭'), ('PAYING', '待支付')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='withdrawmoney',
            name='withdraw_status',
            field=models.CharField(choices=[('0', '处理中'), ('1', '已处理'), ('2', '取消提现')], default='0', max_length=20, verbose_name='提现状态'),
        ),
    ]
