# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-15 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0053_auto_20190115_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WXBusinessInfo',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('PAYING', '待支付'), ('TRADE_CLOSE', '支付关闭'), ('NOTICE_FAIL', '通知失败'), ('TRADE_SUCCESS', '支付成功')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
    ]
