# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-23 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0056_auto_20190115_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='plat_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='平台类型'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('PAYING', '待支付'), ('TRADE_SUCCESS', '支付成功'), ('TRADE_CLOSE', '支付关闭'), ('NOTICE_FAIL', '通知失败')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
    ]
