# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-12 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verify_info',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='预留信息'),
        ),
    ]
