# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-12 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_verify_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_num',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='收款账号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_type',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='银行类型'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='二维码'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_way',
            field=models.CharField(blank=True, choices=[(0, '支付宝'), (1, '微信'), (2, '银行')], max_length=10, null=True, verbose_name='提现方式'),
        ),
    ]
