# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-12 09:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181212_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间'),
        ),
    ]
