# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-14 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_qq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='预留QQ'),
        ),
    ]
