# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-14 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_user_qq'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='用户uid'),
        ),
    ]
