# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-14 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181214_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户uid'),
        ),
    ]
