# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20181214_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用户授权码'),
        ),
    ]
