# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-20 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userprofile_auth_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_qq',
        ),
    ]
