# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-20 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userprofile_qq'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商户回调url'),
        ),
    ]
