# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-25 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20181225_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_money',
            field=models.FloatField(default=0.0, verbose_name='用户总收款'),
        ),
    ]
