# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20181225_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='service_rate',
            field=models.FloatField(default=0.02, verbose_name='提现费率'),
        ),
    ]
