# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-27 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_userprofile_service_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('sort_type', models.CharField(max_length=5, verbose_name='排序权重')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公告管理',
                'verbose_name_plural': '公告管理',
            },
        ),
    ]
