# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_noticeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeinfo',
            name='sort_type',
            field=models.CharField(blank=True, choices=[(0, 'none'), (1, 'new'), (2, 'top')], max_length=5, null=True, verbose_name='排序权重'),
        ),
    ]
