# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20181228_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeinfo',
            name='sort_type',
            field=models.CharField(choices=[(0, 'none'), (1, 'new'), (2, 'top')], default=0, max_length=5, verbose_name='排序权重'),
        ),
    ]
