# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-28 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20181228_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeinfo',
            name='sort_type',
        ),
    ]
