# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-03 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_noticeinfo_sort_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_money',
            field=models.FloatField(default=0.0, verbose_name='当前收款余额'),
        ),
    ]
